name:  CD

on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Release Tag'     
        required: true

env:
  APP_NAME: TestReportGenerator

jobs:
  build: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1']
    permissions:
      contents: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@master
      with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, zip, dom
          ini-values: opcache.jit_buffer_size=256M, opcache.jit=1235, pcre.jit=1, phar.readonly=0, phar.require_hash=0
    - name: Build
      run: |
        cd ..
        php ${{env.APP_NAME}}/build_phar.php
        cd ${{env.APP_NAME}}
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "testreportgenerator.phar"
        tag: ${{ github.event.inputs.tags }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifactErrorsFailBuild: true
    - uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
